name: TF Validate Backend

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  TERRAFORM_VERSION: 1.7.5

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./backend
    steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v2
          with:
            terraform_version: ${{ env.TERRAFORM_VERSION }}
        - name: Init
          run: |
            rm -rf .terraform
            terraform init -backend=false
        - name: Format
          run: terraform fmt -check
        - name: Validate
          run: terraform validate -no-color
